# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4aa50ff720e7bd573e83b695212f7ec69e6fa4d2686a0cc549222534530ccf7cb6c504d70a26969c356b283b5712eb9fc336dda32ab45b7b783dacf17ea4f8f

test:
  secret_key_base: c3f475f8ef94337d1fd786d6926b52fb11bcee3877ece3eca448c8ddfe7904e9aff605b01b08011c8d39f9f941a1cd2f4ef63b51a58a535b3dfedc53305efdeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
